# Generated by Django 5.0.2 on 2024-03-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='e_come\\static\\productsimg')),
                ('name', models.TextField(max_length=130)),
                ('price', models.IntegerField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
