# Generated by Django 5.0.2 on 2024-03-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_products_category_products_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='e_come\\products'),
        ),
    ]
